

CREATE TABLE PFM(

PFM_ID VARCHAR(20) PRIMARY KEY ,
NAME VARCHAR(100) 

);



CREATE TABLE PFM_SCHEME(

SCHEME_ID VARCHAR(20) PRIMARY KEY,
SCHEME_NAME VARCHAR(200) NOT NULL,
PFM_ID VARCHAR(20) NOT NULL,
PFM_NAME VARCHAR(100), 

CONSTRAINT FK_PFM_SCHEMES FOREIGN KEY (PFM_ID) REFERENCES PFM(PFM_ID)

);



CREATE TABLE NAV(
SCHEME_ID VARCHAR(20) NOT NULL,
NAV_DATE DATE NOT NULL,
NAV DOUBLE(20,0),
PRIMARY KEY (SCHEME_ID,NAV_DATE)
);